# 项目相关配置
workflow:
  # 名称
  name: Workflow
  # 版本
  version: 3.6.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/workflow/uploadPath，Linux配置 /home/workflow/uploadPath）
  profile: /home/workflow/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.workflow: debug
    org.springframework: warn

# Spring配置
spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
   # password: 12345
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
  
# MyBatis配置
#mybatis:
#    # 搜索指定包别名
#    typeAliasesPackage: com.workflow.**.domain.entity
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mapper/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #使用spy打印sql日志
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/**/*Mapper.xml
    #  - classpath:/META-INF/modeler-mybatis-mappings/*.xml
  type-aliases-package: com.workflow.**.domain.entity
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
    #枚举
  type-enums-package: com.workflow.process.center.common.enums.entity

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#flowable指标信息暴露在接口 /actuator/flowable
management:
  endpoint:
    flowable:
      enabled: true
#flowable配置
flowable:
  process:
    async:
      executor:
        auto-activate: false
    definition-cache-limit: -1
  database-schema-update: true
  activity-font-name: '宋体'
  label-font-name: '宋体'
  annotation-font-name: '宋体'

# Minio配置
minio:
  url: http://47.96.74.120:9090
  accessKey: cykj
  secretKey: cykj123456
  bucketName: process